spring:
  application:
    name: geohazard-chain
  datasource:
    url: jdbc:postgresql://geohazard-postgis:5432/geohazard?currentSchema=public
    username: postgres
    password: geohazard
    driver-class-name: org.postgresql.Driver

server:
  port: 20231
  servlet:
    context-path: /geohazard-chain

mybatis:
  mapper-locations: classpath:mysqlMapper/*Mapper.xml,classpath:pgsqlMapper/*Mapper.xml,
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    serviceURL:
      defaultZone: http://geohazard-eureka:20222/eureka/
  instance:
    hostname: geohazard-chain




geoserver:
  username: admin
  password: geoserver
  hostname: geohazard-geoserver
  port: 8080


geoserverURL:
  IP: www.rsgisai.com
  PORT: 8080



Module4:
  PATH: /home/code_space/py_test_demo/DEM51.tif

logging:
  level:
    com:
      rsgisai:
        geohazard:
          level: DEBUG
