spring:
  application:
    name: auth-service
  profiles:
    active: datasource

server:
  port: 20221
  servlet:
    context-path: /auth-service

mybatis:
  mapper-locations: classpath:mysqlMapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:20222/eureka/
  instance:
    hostname: localhost