### Get GHDSL
GET http://localhost:20234/risk-level/susceptibility/operator


### operate
POST http://localhost:20234/risk-level/probability/earthquake
Content-Type: application/json

{
  "workingAreaId": 1,
  "userId": 1,
  "arguments": {
    "susceptibilityWeight": 50,
    "earthquakeWeight": 50
  }
}
