### 计算危险性，返回计算结果图层
POST http://localhost:20234/risk-level/wxx/wxxevaluation
Content-Type: application/x-www-form-urlencoded

workingAreaId=1


### 计算危险性，返回计算结果图层
POST http://localhost:20234/risk-level/wxx/evaluation
Content-Type: application/x-www-form-urlencoded

workingAreaId=1

### 获取图层名称
GET http://localhost:20234/risk-level/wxx/layerName?workingAreaId=1
