spring:
  application:
    name: influence-scope-statistic
  profiles:
    active: datasource

server:
  port: 20233
  servlet:
    context-path: /influence-scope-statistic

mybatis:
  mapper-locations: classpath:mysqlMapper/*Mapper.xml,classpath:pgsqlMapper/*Mapper.xml,

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:20222/eureka/
  instance:
    hostname: localhost