###
GET http://localhost:20221/auth-service/sys-user

###
POST http://localhost:20221/auth-service/sys-user
Content-Type: application/x-www-form-urlencoded

username=test1&password=123456

###
POST http://localhost:20221/auth-service/sys-user
Content-Type: application/x-www-form-urlencoded

username=root&password=123456

