### 获取DSL
GET http://localhost:20241/geospatial-computation/composition-operator?name=GH_Susceptibility
Content-Type: application/json

###
POST http://localhost:20241/geospatial-computation/composition-operator/operate
Content-Type: application/json

{
  "name": "slope_reclassify",
  "arguments": {
    "numberClasses": 5
  }
}

###
POST http://localhost:20241/geospatial-computation/composition-operator/submit
Content-Type: application/json

{
  "workingAreaId": 11,
  "userId": 1,
  "name": "GH_Susceptibility",
  "arguments": {
    "demNumberClasses": 5,
    "slopeNumberClasses": 2,
    "aspectNumberClasses": 3
  }
}

### 危险性计算
POST http://localhost:20241/geospatial-computation/composition-operator/submit
Content-Type: application/json

{
  "workingAreaId": 11,
  "userId": 1,
  "name": "GH_Probability",
  "arguments": {
    "precipitationWeight": 3100,
    "susceptibilityWeight": 6900
  }
}
