


POST http://localhost:20231/geohazard-chain/sys/Algorithm
Content-Type: application/json

{
  "dhwxx_number": "53011301053R",
  "dhwxx_with": 60.00,
  "dhwxx_depth": 100.00,
  "dhwxx_l1": 160.00
}