
//public  resultType<Boolean> fun(@RequestParam("number")String number,@RequestParam("width")Double with,@RequestParam("depth") Double depth,@RequestParam("l1")Double l1)
//河流宽度取60
//l1取160
POST http://localhost:20231/sys/Algorithm
Content-Type: application/json

{
     "number": "53011301040R",
     "with": 60.00,
     "depth": 100.00,
     "l1": 160.00
}