POST http://localhost:20231/geohazard-chain/sys/Algorithm
Content-Type: application/json



  [
    {
      "id": "53011301105R",
      "SlopeHeight": 1274.52,
      "WithDepthRatio": 4.53,
      "WithIndex": 41.0,
      "BuDuiChengRatio": 1.12,
      "AverageSlop": 29.8,
      "Area": 2.96
    },
    {
      "id": "53011301060R",
      "SlopeHeight": 633.9669,
      "WithDepthRatio": 2.76374,
      "WithIndex": 110.52810,
      "BuDuiChengRatio": 2.62069,
      "AverageSlop": 27.52754,
      "Area": 0.5682504736
    },
    {
      "id": "53011301040R",
      "SlopeHeight": 473.0,
      "WithDepthRatio": 3.58,
      "WithIndex": 46.0,
      "BuDuiChengRatio": 1.8985,
      "AverageSlop": 37.3696,
      "Area": 0.856233
    }
  ]

