POST http://localhost:20231/geohazard-chain/sys1/algorithem
Content-Type: application/json

{
  "numDem": 4,
  "numSlop": 5,
  "numAspect": 8,
  "numCurvature": 7,
  "numWater": 6,
  "numRainFall": 3,
  "numRock": 2
}