spring:
  application:
    name: risk-level
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://122.112.250.145:13306/geohazard?useSSL=false&useUnicode=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: Mining2021@zhq
    pgsql:
      #      注意：这里 currentSchema 必须设置为 public ，不然没有办法使用空间函数 "ST_*"
      url: jdbc:postgresql://122.112.250.145:15432/geohazard?currentSchema=public
      username: geohazard
      password: cumtb_2023_rerssil
      driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 6000000 # 6000 s 100 minute

server:
  port: 20234
  servlet:
    context-path: /risk-level

mybatis:
  mapper-locations: classpath:mysqlMapper/*Mapper.xml,classpath:pgsqlMapper/*Mapper.xml,
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:20222/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com:
      rsgisai:
        geohazard:
          level: DEBUG

geoserver:
  username: admin
  password: geoserver
  hostname: www.rsgisai.com
  port: 8080


geoserverURL:
  IP: www.rsgisai.com
  PORT: 8080
