eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:20222/eureka/
  instance:
    hostname: geohazardMain



spring:
  application:
    name: geohazardMain
  datasource:
    driver-class-name: org.postgresql.Driver
    username: geohazard
    password: cumtb_2023_rerssil
    url:  jdbc:postgresql://122.112.250.145:15432/geohazard?currentSchema=public



server:
  port: 20888
  servlet:
    context-path: /geohazardmain


# 配置 feign 默认请求时间仅几秒钟，配置请求时间长一些(毫秒)
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
  hystrix:
    enabled: false    # 不要开启hystrix，会导致超时配置不生效